### ISSUE TITLE
Websocket error: no close frame received or sent

### ISSUE THREAD

**Issue by NobbisCrypto** [NobbisCrypto/Crypto#1]
Full error message:

```
Unexpected error: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/protocol.py", line 944, in transfer_data
    message = await self.read_message()
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/protocol.py", line 1013, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/protocol.py", line 1089, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/protocol.py", line 1144, in read_frame
    frame = await Frame.read(
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hodloo-alerts-api.py", line 84, in <module>
    loop.run_until_complete(consume(config.HODLOO_URI))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "hodloo-alerts-api.py", line 70, in consume
    await consumer_handler(websocket)
  File "hodloo-alerts-api.py", line 65, in consumer_handler
    async for message in websocket:
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/protocol.py", line 481, in aiter
    yield await self.recv()
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/protocol.py", line 552, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.8/dist-packages/websockets/legacy/protocol.py", line 920, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
```

Looks like a network connection issue. I could handle it in the script and start the loop again.

Workaround: add `autorestart=true` to the supervisor config file to restart the script automatically.

**Comment by NobbisCrypto** [comment]
Fixed
